set nocompatible
set showmode
set showcmd
set mouse=a
set encoding=utf-8
filetype indent on
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set number
set textwidth=80
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set undofile
set wildmenu
set wildmode=longest:list,full
set t_Co=256
syntax enable
set background=light
let g:solarized_termcolors=256
colorscheme solarized
