#!/usr/bin/tclsh

# Copyright 2003-2013 Interactive Motion Technologies, Inc.
# Watertown, MA, USA
# http://www.interactive-motion.com
# All rights reserved

# starts 

global ob

set ob(crobhome) $::env(CROB_HOME)

global ob

source $ob(crobhome)/shm.tcl

puts "loading robot process."
start_lkm
start_shm

wshm ankle_stiff .30
wshm ankle_damp .001

set x 0.0
set y 0.0

start_loop

set n 20.0
set a(0) [list -$n $n 0.0 0.0]
set a(1) [list $n $n 0.0 0.0]
set a(2) [list $n -$n 0.0 0.0]
set a(3) [list -$n -$n 0.0 0.0]

after 100

acenter -$n $n

set donevar 0
set i 0

set slottime 1000
set etime $slottime
set mtime [expr {int($slottime / 1000. * 200.)}]
every $etime {
	if {!$::donevar} {
	set j [expr {$::i % 4}]
	set k [expr {($::i + 1) % 4}]
	set m "movebox 0 8 {0 $::mtime 1} [list $::a($j)] [list $::a($k)]"
	puts "$::i: $m"
	eval $m
	incr ::i
	if {$::i > 100} {set ::donevar 1}
	}
}

proc done {} {
# lower ankle
adone
puts "unloading robot process"
stop_loop
stop_shm
stop_lkm
}

vwait donevar

done
