#!/usr/bin/tclsh

# Copyright 2003-2013 Interactive Motion Technologies, Inc.
# Watertown, MA, USA
# http://www.interactive-motion.com
# All rights reserved

# acenter - g2 proto ankle calibration derived from forcecenter

package require Tk

proc done {} {
stop_loop
stop_shm
stop_lkm
exit 0
}

wm withdraw .

font create default -family Times -size 18
option add *font default

global ob

proc tksleep {time} {
	after $time set ::tksleep_end 1
	vwait ::tksleep_end
}

set ob(crobhome) $::env(CROB_HOME)
source $ob(crobhome)/shm.tcl

set ob(current_robot) [current_robot]

if {!([is_robot_ready] || [info exists ::env(IGNORE57)])} {
	tk_messageBox -title Failed -message "The Ready lamp is not lit.\
Please release all Stop buttons,\
press the Start button, and try again."
	exit 1
}

puts "Loading robot process."

if {[personality_is g2]} {
    # start CAN 
    # ob(naxes) contains the number of axes that responded to the CAN reset.
    set ob(detectednaxes) [exec $ob(crobhome)/tools/robsetup]
    
    if {$ob(detectednaxes) == 13} {
	tk_messageBox -title Failed -message "Not all axes are configured with a valid CAN ID."
	exit 1
    }

    if {$ob(detectednaxes) == 14} {
	tk_messageBox -title Failed -message "No axes were found."
	exit 1
    }

    if {$ob(detectednaxes) == 15} {
	tk_messageBox -title Failed -message "robsetup found an unrecognized robot type in current_robot."
	exit 1
    }

    if {$ob(detectednaxes) == 16} {
	tk_messageBox -title Failed -message "This robot is configured as a $ob(current_robot), but not enough axes were available."
	exit 1
    }

    if {$ob(detectednaxes) == 17} {
	tk_messageBox -title Failed -message "The Ready lamp is not lit.\
Please release all Emergency Stops,\
press the Start button, and try again."
	exit 1
    }

    if {($ob(current_robot) == "ankle" && $ob(detectednaxes) < 2) } {
	    tk_messageBox -title Failed -message "This robot is configured as a $ob(current_robot), but only $ob(detectednaxes) axes are available."
	    exit 1
    }

}

if {$ob(current_robot) != "ankle"} {
	tk_messageBox -title Failed -message "This robot is configured as a $ob(current_robot)\
and you are trying to calibrate it as a ankle."
	exit 1
}
# start the robot process, shared memory, and the control loop
# puts "loading robot process"
if {[is_lkm_loaded]} {
	puts "lkm already loaded, exiting."
	exit 1
} else {
	##wm protocol . WM_DELETE_WINDOW done
	start_lkm
}

start_shm

tksleep 100

wshm ankle_stiff 50.0
wshm ankle_damp 1.0

# start in open loop mode
wshm test_raw_torque 1
# no damping zone
wshm no_safety_check 1

# check that this is an ankle

set ob(have_ankle) 0
set ob(have_ankle) [rshm have_ankle]

start_loop

# sleep for .1 sec, gives robot chance to start
tksleep 100

# turn off cal bit, will only be turned on if the cal succeeds.
clear_robot_cal_done

tk_messageBox -title "Ankle Calibration" -icon warning -message "Move links to calibration point, then press OK to set calibration."

# zero encoders
if {[personality_is g2]} {
    exec $ob(crobhome)/tools/canenc_zero
}
if {[personality_is ce]} {
    wshm pcienc_zero 1
}

tksleep 100

# good cal, turn on cal bit
set_robot_cal_done

wshm test_raw_torque 0

tksleep 100

tk_messageBox -title Complete -message "Calibration Complete"

# puts "unloading robot process"

done
