#!/usr/bin/tclsh

# Copyright 2005-2013 Interactive Motion Technologies, Inc.
# Watertown, MA, USA
# http://www.interactive-motion.com
# All rights reserved

# dout square wave user mode
# not realtime precise, but not bad.
# arg is time in seconds

global ob

set ob(crobhome) $::env(CROB_HOME)

source $ob(crobhome)/shm.tcl

# start the robot process, shared memory, and the control loop
puts "loading robot process"
if {[is_lkm_loaded]} {
	puts "lkm already loaded."
} else {
	start_lkm
}
start_shm

start_loop

set Hz 200
wshm restart_Hz $Hz
wshm restart_go 1
after 100

set ntick 1
wshm ntickfifo $ntick
puts "tick rate ($ntick / $Hz) ms"

set tickfd [open /proc/xenomai/registry/native/pipes/crob_tick]

set num 10
if {$argc == 1} {
    set num [lindex $argv 0]
}
set num [expr {$num * $Hz / $ntick}]

for {set i 0} {$i < $num} {incr i} {
	gets $tickfd
	set sq [expr {$i %2}]
        exec $ob(crobhome)/tools/ucdout --pin 0 --set $sq
        exec $ob(crobhome)/tools/ucdout --pin 1 --set $sq
        exec $ob(crobhome)/tools/ucdout --pin 2 --set $sq
        exec $ob(crobhome)/tools/ucdout --pin 3 --set $sq
	puts "tick $i $sq"
}

exec $ob(crobhome)/tools/ucdout --pin 0 --set 0
exec $ob(crobhome)/tools/ucdout --pin 1 --set 0
exec $ob(crobhome)/tools/ucdout --pin 2 --set 0
exec $ob(crobhome)/tools/ucdout --pin 3 --set 0

close $tickfd

puts "unloading robot process"

stop_loop
stop_shm
stop_lkm
