#! /bin/bash

# get status of robot resources

# echo the headers that the basic status progs print,
# because we filter them out when grepping (except for lsof)

if [[ ! -e $IMT_CONFIG/current_robot ]]; then
	echo file $IMT_CONFIG/current_robot does not exist.
	exit 1
fi

echo Application version:
ls -l /opt/imt/robot
echo

echo Current Robot Type: `cat $IMT_CONFIG/current_robot`
echo

echo IMT Environment Variables:
for i in CROB_HOME LGAMES_HOME I18N_HOME IMAGES_HOME PROTOCOLS_HOME ROBOT_HOME THERAPIST_HOME LOG_HOME IMT_CONFIG; do
echo $i=${!i}
done
echo

echo Open Files:
# lsof prints a goofy warning that we ignore with -w
lsof -n -w -c robot -c shm -c atinetft -c mccd -c heartbeat -c iofifo -c rwarp -c rtcanrecv -c rtcansend -c rtcaninit -c ucplc -c notifyerror -c plc -c g2plc -c ceplc
echo

echo Real-time Processes:
rtps
echo

echo Running Processes:
echo "UID        PID  PPID   LWP  C NLWP STIME TTY          TIME CMD"
ps -efL | grep -w -i -E 'robot|shm|atinetft|mccd|heartbeat|ififo|rwarp|rtcan|ucplc|notifyerror' | grep -v grep
echo

echo Allocated Shared Memory:
echo "key        shmid      owner      perms      bytes      nattch     status"
# 494D543[1-4] are the IMT shm areas
ipcs -m | grep -i -E '494D543|494D544'
