#! /bin/bash
# get dat log file body

if [[ ! -r "$1" ]]; then
	echo datbody: file \"$1\" is not readable. 1>&2
	exit 1
fi

top=$(sed 1q $1)

if [[ $top != "# imt log" ]]; then
	echo datbody: $1 is not an imt log file. 1>&2
	exit 1
fi

# Note: sed isn't guaranteed to handle binary data, but in this case,
# it's just skipping a plaintext header and printing the rest to
# stdout untouched.  it seems to work.

# delete until #####, print the rest.
sed '1,/^#####$/d' < $1
